
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Table table1;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	private global::Gtk.Entry txtDataBase;

	private global::Gtk.Entry txtPassWord;

	private global::Gtk.Entry txtServer;

	private global::Gtk.Entry txtTimeOut;

	private global::Gtk.Entry txtUserID;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox3;

	private global::Gtk.CheckButton chkPooling;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label7;

	private global::Gtk.Entry txtMinPool;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label8;

	private global::Gtk.Entry txtMaxPool;

	private global::Gtk.Label GtkLabel2;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button btnOk;

	private global::Gtk.Button btnCancel;

	private global::Gtk.Label lbStatus;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Probar conexión a PostgreSQL");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Server");
		this.table1.Add (this.label1);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("DataBase");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("User ID");
		this.table1.Add (this.label3);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
		this.table1.Add (this.label4);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Timeout");
		this.table1.Add (this.label5);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.label5]));
		w5.TopAttach = ((uint)(4));
		w5.BottomAttach = ((uint)(5));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtDataBase = new global::Gtk.Entry ();
		this.txtDataBase.CanFocus = true;
		this.txtDataBase.Name = "txtDataBase";
		this.txtDataBase.IsEditable = true;
		this.txtDataBase.InvisibleChar = '●';
		this.table1.Add (this.txtDataBase);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.txtDataBase]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtPassWord = new global::Gtk.Entry ();
		this.txtPassWord.CanFocus = true;
		this.txtPassWord.Name = "txtPassWord";
		this.txtPassWord.IsEditable = true;
		this.txtPassWord.Visibility = false;
		this.txtPassWord.InvisibleChar = '●';
		this.table1.Add (this.txtPassWord);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.txtPassWord]));
		w7.TopAttach = ((uint)(3));
		w7.BottomAttach = ((uint)(4));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtServer = new global::Gtk.Entry ();
		this.txtServer.CanFocus = true;
		this.txtServer.Name = "txtServer";
		this.txtServer.IsEditable = true;
		this.txtServer.InvisibleChar = '●';
		this.table1.Add (this.txtServer);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.txtServer]));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtTimeOut = new global::Gtk.Entry ();
		this.txtTimeOut.CanFocus = true;
		this.txtTimeOut.Name = "txtTimeOut";
		this.txtTimeOut.IsEditable = true;
		this.txtTimeOut.InvisibleChar = '●';
		this.table1.Add (this.txtTimeOut);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.txtTimeOut]));
		w9.TopAttach = ((uint)(4));
		w9.BottomAttach = ((uint)(5));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtUserID = new global::Gtk.Entry ();
		this.txtUserID.CanFocus = true;
		this.txtUserID.Name = "txtUserID";
		this.txtUserID.IsEditable = true;
		this.txtUserID.InvisibleChar = '●';
		this.table1.Add (this.txtUserID);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.txtUserID]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.chkPooling = new global::Gtk.CheckButton ();
		this.chkPooling.CanFocus = true;
		this.chkPooling.Name = "chkPooling";
		this.chkPooling.Label = global::Mono.Unix.Catalog.GetString ("Habilitar Pooling");
		this.chkPooling.Active = true;
		this.chkPooling.DrawIndicator = true;
		this.chkPooling.UseUnderline = true;
		this.hbox3.Add (this.chkPooling);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.chkPooling]));
		w12.Position = 0;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Limite mínimo del pool");
		this.hbox4.Add (this.label7);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label7]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.txtMinPool = new global::Gtk.Entry ();
		this.txtMinPool.CanFocus = true;
		this.txtMinPool.Name = "txtMinPool";
		this.txtMinPool.IsEditable = true;
		this.txtMinPool.MaxLength = 2;
		this.txtMinPool.InvisibleChar = '●';
		this.hbox4.Add (this.txtMinPool);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.txtMinPool]));
		w15.Position = 1;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Límite Máximo del Pool");
		this.hbox5.Add (this.label8);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label8]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.txtMaxPool = new global::Gtk.Entry ();
		this.txtMaxPool.CanFocus = true;
		this.txtMaxPool.Name = "txtMaxPool";
		this.txtMaxPool.IsEditable = true;
		this.txtMaxPool.MaxLength = 3;
		this.txtMaxPool.InvisibleChar = '●';
		this.hbox5.Add (this.txtMaxPool);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.txtMaxPool]));
		w18.Position = 1;
		this.vbox2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.GtkAlignment2.Add (this.vbox2);
		this.frame1.Add (this.GtkAlignment2);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Pooling de conexiones</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel2;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnOk = new global::Gtk.Button ();
		this.btnOk.CanFocus = true;
		this.btnOk.Name = "btnOk";
		this.btnOk.UseStock = true;
		this.btnOk.UseUnderline = true;
		this.btnOk.Label = "gtk-ok";
		this.hbox2.Add (this.btnOk);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnOk]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnCancel = new global::Gtk.Button ();
		this.btnCancel.CanFocus = true;
		this.btnCancel.Name = "btnCancel";
		this.btnCancel.UseStock = true;
		this.btnCancel.UseUnderline = true;
		this.btnCancel.Label = "gtk-quit";
		this.hbox2.Add (this.btnCancel);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnCancel]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.lbStatus = new global::Gtk.Label ();
		this.lbStatus.Name = "lbStatus";
		this.lbStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("Status");
		this.hbox2.Add (this.lbStatus);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lbStatus]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w26.Position = 2;
		w26.Expand = false;
		w26.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 326;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.chkPooling.Toggled += new global::System.EventHandler (this.OnChkPoolingToggled);
		this.btnOk.Clicked += new global::System.EventHandler (this.OnBtnOkClicked);
		this.btnCancel.Clicked += new global::System.EventHandler (this.OnBtnCancelClicked);
	}
}
